### ISSUE TITLE
Podpora pre novy Panelak

### ISSUE THREAD

**Issue by marki555** [kodi-czsk/plugin.video.joj.sk#1]
Panelak ma momentalne inu strukturu stranky, archiv je na URL http://novaseria.joj.sk/p/epizody , zoznam epizod sa uz netaha cez ajax, ale submituje sa formular cez post (funguje aj get). Pozeral som zdrojaky pluginu, ale neviem ako to tam zakomponovat kedze treba pridat vynimky na viacere miesta (zoznam serii, zoznam epizod, vymenit hlavne url a pod.)

**Comment by mx3L** [comment]
diky, opravene

**Comment by mx3L** [comment]
Diky, opravene
