### ISSUE TITLE
Neprehraje zadne video

### ISSUE THREAD

**Issue by InToSSH** [kodi-czsk/plugin.video.joj.sk#11]
Plugin jsem dnes zkoušel na několika různých pořadech a v Kodi 15.0 nepřehraje nic, lze vybrat kvalitu, poté buď se nic neděje, nebo vyskočí hláška, že info je v logu.

[kodi_joj_log.txt](https://github.com/kodi-czsk/plugin.video.joj.sk/files/63467/kodi_joj_log.txt)

Snad půjde nějak opravit. Díky

**Comment by mx3L** [comment]
Ahoj,
prehravanie momentalne funguje.

V logu vidim
`2:40:38 T:140277104760576   ERROR: Unable to load librtmp.so.1, reason: librtmp.so.1: cannot open shared object file: No such file or directory.

Cize problem je s chybajucou librtmp kniznicou.
`

**Comment by InToSSH** [comment]
Ahoj,
ano, moje chyba, nevím proč ale přeložil jsem si to jako že knihovna nemůže otevřít stream.V Kodi je defaultně obsažená knihovna librtmp.so.0, ale ne librtmp.so.1.
Pokud to někomu pomůže, v Ubuntu stačí:
```
sudo apt-get install librtmp1
```
Každopádně děkuji za odpověď, už to šlape jak má a já kvůli své slovenské přitelkyni nemusím vstávat od telky :)
