### ISSUE TITLE
Nefunkční po aktualizaci webu

### ISSUE THREAD

**Issue by InToSSH** [kodi-czsk/plugin.video.joj.sk#12]
Addon prestal fungovat po tom co jojka aktualizovala web. Bude prosím možné opravit? 
Díky moc

**Comment by mx3L** [comment]
Ahoj, uz som sa do toho pustil snad to zachvilu bude

**Comment by mx3L** [comment]
Tak hotovo, snad to bude ok

**Comment by InToSSH** [comment]
Díky za opravu,
jen u některých videí nejde přehrát 360p, a např 15. minut Kuchar vubec, ale to může být chyba na serveru joj, ale nejde ani JOJ Live stream, Plus a Wau fungují. Pokud bude potřeba, otestuji dál a případně pošlu logy.

**Comment by mx3L** [comment]
Vdaka za info. Ktore 360p nefunguju? 
Ostatne opravene..

**Comment by bodyguardroman** [comment]
predoslej verzii pluginu bola položka Latest video(zozbierane vsetky posledne videa z joj,plus,wau,senzi)
Dala by sa  ta položka doplniť?

**Comment by mx3L** [comment]
Ma joj stranku kde mozem najst posledne pridane videa?

Mozno horna cast hlavnej stranky archivov? 
http://www.joj.sk/archiv
http://plus.joj.sk/archiv
http://wau.joj.sk/archiv

**Comment by bodyguardroman** [comment]
predoslej verzii pluginu bola položka Latest video(zozbierane vsetky posledne videa z joj,plus,wau,senzi)
Dala by sa  ta položka doplniť?

**Comment by bodyguardroman** [comment]
no nemaju to:(
mimochodom to live vysielanie  joj funguje,ale prečo v najnižšiej kvalite? na webe je aj hd.
dalo by sa dat vybrat kvalita?alebo by stačilo ta HD.

**Comment by InToSSH** [comment]
@mx3L noo, teď po update na 1.2.8 se mi bohužel v JOJ neukazuje vůbec nic, je to prázdné, Plus a WAU se vylistují, ale JOJ ne, zkoušel jsem i reinstall a reboot a furt nic.

**Comment by mx3L** [comment]
@bodyguardroman 
bol s tym problem:
https://github.com/kodi-czsk/plugin.video.joj.sk/pull/2/commits/89ea8dae891d9ed3ba7ae3e28aa3d052cbd0f162
Mozno sa situacia odvtedy zmenila. Este sa na to pozriem.

@InToSSH 
Zrejme je problem, ze som pridal www subdomenu, u mna ale na SVK vsetko funkcne. 
Kazdopadne som to vratil spat v dalsej verzii(1.2.9) napis prosim ci to uz funguje.

**Comment by InToSSH** [comment]
@mx3L Už se zdá všechno funkční, díky moc.
Jen poslední věc, že u většiny relací je nějak divné číslování epizod, např. u Habovřesky jsou první tři díly ve formátu: (S01 E01) - Habovřesky 1 a pak dál je to: Habovřesky 5 1.séria - 5.diel .. Ale to už je no big deal, hlavně že to šlape :)

**Comment by mx3L** [comment]
@InToSSH 
Ano viem o tom, pozri napriklad http://www.joj.sk/noviny-o-17-00/archiv/2016-07-04-noviny-o-17-00
posledne tri televizne noviny (s obrazkom) maju uvedeny len nazov bez datumu, cize tu nevidim vela moznosti, mozno predpokladat datum, cast na zaklade toho co je v tabulke epizod pod tym?

Nevidim to ale ako velmi nutne to riesit hlavne ze to funguje :)

@bodyguardroman 
Pozrel som tie live streamy, situacia sa ale nezmenila cize max 540p.
