### ISSUE TITLE
ARCHÍV POSLEDNÉ EPIZÓDY

### ISSUE THREAD

**Issue by bodyguardroman** [kodi-czsk/plugin.video.joj.sk#13]
všetko funguje,avšak ked pridaju videa na webovu stranku mimo zlozky,sa kodi nezobrazia:
napr.
http://nasi.joj.sk
na webe su nove diely v kodi je iba zložka 1.seria.
Dalo by sa to spravit aby to nacitavalo nove diely (latest episodes)?

**Comment by mx3L** [comment]
Zda sa ze to uz opravili:
http://nasi.joj.sk/epizody/2016-09-13-cely-tyzden

**Comment by bodyguardroman** [comment]
jj mas pravdu,to som nevedel,že ked to oni na webe urobia že to pojde aj v kodi.

**Comment by mx3L** [comment]
ano, polozky sa nacitavaju priamo za stranok joj
