### ISSUE TITLE
Cant install on Windows Kodi v17 Beta 3

### ISSUE THREAD

**Issue by rickselest** [kodi-czsk/plugin.video.joj.sk#16]
Can't install on Kodi 17 for windows. Getting a "Fail to install  dependencies" error. Tried 1.3.1

**Comment by mx3L** [comment]
You're probably missing script.module.stream.resolver.

I suggest to install joj.sk plugin from kodi-czsk repository, it should also install necessary dependencies like script.module.stream.resolver.

http://kodi-czsk.github.io/repository/repo/repository.kodi-czsk/repository.kodi-czsk-1.0.2.zip
