### ISSUE TITLE
Chyba pri spustený 

### ISSUE THREAD

**Issue by pskala7** [kodi-czsk/plugin.video.joj.sk#18]
Pri spustení vyskočí chyba.
Ide o zariadenie: raspberry pi2 LibreElec 7.0.3

V logu som nasiel:
```
Error Contents: No module named util
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.joj.sk/default.py", line 24, in <module>
import joj
File "/storage/.kodi/addons/plugin.video.joj.sk/resources/lib/joj.py", line 30, in <module>
import util
ImportError: No module named util
-->End of Python script error report<--
```

**Comment by mx3L** [comment]
Asi ti chyba script.module.stream.resolver, nainstaluj joj doplnok z kodi-czsk repozitara a nebudes mat problem.
https://kodi-czsk.github.io/repository/repo/repository.kodi-czsk/repository.kodi-czsk-1.0.2.zip

**Comment by pskala7** [comment]
Pohomohlo
