### ISSUE TITLE
nejde

### ISSUE THREAD

**Issue by bodyguardroman** [kodi-czsk/plugin.video.joj.sk#23]
menili niečo na webe.
error:playlist player skipping unplayble item  0 path.
Nejde nič prehrať

**Comment by rasto1307** [comment]
Zdravim,
Skusal som upravy v joj.py vymazal som skompilovany joj.pyo a spustil znovu, ale chyba pretrvava.
tu je cast logu:
19:27:36.499 T:140081499207424  NOTICE: ["Initializing provider joj.sk with settings {'lang': '0', 'downloads': '', 'quality': '0'}"]
19:27:38.766 T:140081499207424  NOTICE: Previous line repeats 1 times.
19:27:38.766 T:140081499207424  NOTICE: ['[joj.sk] list http://joj.sk']
19:27:38.766 T:140081499207424  NOTICE: ['[joj.sk] list_base http://joj.sk/archiv-filter']
19:27:40.038 T:140081490814720 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.joj.sk/?play=687474703a2f2f6a6f6a2e736b2f6c6976652e68746d6c&cp=6a6f6a2e736b&
19:27:40.038 T:140081490814720   ERROR: InputStream: Error opening, plugin://plugin.video.joj.sk/?play=687474703a2f2f6a6f6a2e736b2f6c6976652e68746d6c&cp=6a6f6a2e736b&
19:27:42.103 T:140081499207424  NOTICE: ["Initializing provider joj.sk with settings {'lang': '0', 'downloads': '', 'quality': '0'}"]
19:27:42.103 T:140081499207424  NOTICE: ['[joj.sk] list https://www.joj.sk/15-min-kuchar/archiv/2017-09-22-15-minut-kuchar#s']
19:27:42.103 T:140081499207424  NOTICE: ['[joj.sk] list_show https://www.joj.sk/15-min-kuchar/archiv/2017-09-22-15-minut-kuchar#s']
19:27:46.442 T:140081499207424  NOTICE: ["Initializing provider joj.sk with settings {'lang': '0', 'downloads': '', 'quality': '0'}"]
19:27:46.442 T:140081499207424  NOTICE: ['[joj.sk] list https://www.joj.sk/15-min-kuchar/archiv/2017-09-22-15-minut-kuchar?season=577']
19:27:46.442 T:140081499207424  NOTICE: ['[joj.sk] list_show https://www.joj.sk/15-min-kuchar/archiv/2017-09-22-15-minut-kuchar?season=577']
19:27:49.573 T:140081499207424  NOTICE: ["Initializing provider joj.sk with settings {'lang': '0', 'downloads': '', 'quality': '0'}"]
19:27:49.992 T:140081499207424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'context'
                                            Traceback (most recent call last):
                                              File "/home/rasto/.kodi/addons/plugin.video.joj.sk/default.py", line 52, in <module>
                                                XBMCJojContentProvider(provider,settings,__addon__).run(params)
                                              File "/home/rasto/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 87, in run
                                                return self.play({'url': params['play'], 'info': params})
                                              File "/home/rasto/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 186, in play
                                                stream = self.resolve(item['url'])
                                              File "/home/rasto/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 346, in resolve
                                                return self.provider.resolve(item, select_cb=select_cb)
                                              File "/home/rasto/.kodi/addons/plugin.video.joj.sk/resources/lib/joj.py", line 209, in resolve
                                                pageid = urlparse.parse_qs(iframe_url)['context'][0]
                                            KeyError: 'context'
                                            -->End of Python script error report<--
19:27:50.055 T:140082920372224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.joj.sk/?play=68747470733a2f2f7777772e6a6f6a2e736b2f31352d6d696e2d6b75636861722f6172636869762f323031362d30312d32342d31352d6d696e2d6b75636861722d7072656d69657261&cp=6a6f6a2e736b&]

**Comment by mx3L** [comment]
Ahojte, diky za report, malo by byt fixnute v 1.3.3

**Comment by jdemovic** [comment]
Super,
vo v1.3.3 funguje.
