### ISSUE TITLE
JOJ Plus Oktagon

### ISSUE THREAD

**Issue by hitman222** [kodi-czsk/plugin.video.joj.sk#25]
Nemozes sa pozriet na prve dva diely Oktagon MMA Vyzva ,vyskakuje chyba.
Dakujem.
[log-2017-10-06-07.44.17.zip](https://github.com/kodi-czsk/plugin.video.joj.sk/files/1361935/log-2017-10-06-07.44.17.zip)

**Comment by jose1711** [comment]
prosim pozri znova, mne to funguje

**Comment by jose1711** [comment]
no response, closing
