### ISSUE TITLE
nefunguje live prehravanie joj

### ISSUE THREAD

**Issue by jose1711** [kodi-czsk/plugin.video.joj.sk#26]
miesto prehravania live vysielania sa spusti kratka slucka "zaseknuteho" videa, na webe vsetko ok

**Comment by Gummak** [comment]
U mňa to nie je ani slučka, ale iba zaseknutý obraz pána v okuliaroch. :-(

**Comment by jose1711** [comment]
je to playlist, aj ked sa to tak nejavi

**Comment by tomtom02** [comment]
ja to mam tak isto - pan v okuliaroch na joj, 
reklama na mini elektro radiator co sa zasekne na jojPlus, a wuao som radsej ani nezapol.
Mam Kodi v16, funkcny asi rok, az doteraz, vsetko okrem Jojky funguje.
Ked skusim stream cez googleChrome, vsetko slape ako hodinky.

Reinstall nepomohol. Pomoze novsi Kodi ? asi tazko, ked je to stale ten isty plugin.
Ako to vyriesit ?

**Comment by tomtom02** [comment]
v inom threade niekto napisal ze: 

Po uprave joj.py
zmenena adresa z https://nn.geo.joj.sk/ na http://nn.geo.joj.sk/
vsetko vyzera, ze funguje spravne....

source: https://github.com/kodi-czsk/plugin.video.joj.sk/issues/21

**Comment by Gummak** [comment]
OK, zmeniť adresu v doplnku. Ale ako?

**Comment by jose1711** [comment]
skuste
```kodi-send --action="PlayMedia(https://nn.geo.joj.sk/live/hls/joj-720.m3u8)"```

**Comment by tomtom02** [comment]
To neviem kde zadat. Nevie niekto updatini ten plugin globálne?

**Comment by jose1711** [comment]
mozte vyskusat updatnuty fork: https://github.com/jose1711/plugin.video.joj.sk

**Comment by jose1711** [comment]
urobil som PR: https://github.com/kodi-czsk/plugin.video.joj.sk/pull/27

**Comment by tomtom02** [comment]
Funguje!
Bravo,

Dik

**Comment by Gummak** [comment]
Po aktualizácii na 1.3.4 funguje.
Díky chlapi.
