### ISSUE TITLE
panelak - latest series not shown

### ISSUE THREAD

**Issue by leos23** [kodi-czsk/plugin.video.joj.sk#3]
Latest series of panelak are not shown, the list ends with series 13. Probable reason is that they have changed the url for last series - novaseria.joj.sk/p/archiv

**Comment by mx3L** [comment]
Thanks, should be fixed now

**Comment by leos23** [comment]
In which version? Updated the add-on yesterday via Kodi and it still did not work.

**Comment by mx3L** [comment]
1.2.2, it should be in auto-updates in hour

**Comment by leos23** [comment]
Fixed in 1.2.2, works fine.
