### ISSUE TITLE
Stale chyba popis epizod v nazve streamu

### ISSUE THREAD

**Issue by haragiro** [kodi-czsk/plugin.video.joj.sk#32]
Stale chyba popis epizod v nazve streamu napr. Hotel Paradise

**Comment by kapitan-iglu** [comment]
Ale cisla epizod nie su zobrazene ani na oficialnej stranke pri [vypise epizod](https://videoportal.joj.sk/hotel-paradise/epizody)...

**Comment by jose1711** [comment]
closing as invalid
