### ISSUE TITLE
Zobrazovanie stranok v archive

### ISSUE THREAD

**Issue by rasto1307** [kodi-czsk/plugin.video.joj.sk#33]
Nefunguju dalsie podstranky v archive po zvoleni konkretnej serie...Napr. ak si dam hociktoru seriu sudnej siene v archive tv JOJ  cez plugin joj v kodi zobrazi mi prvych 16 epizod  a to je vsetko...Ak si tu istu istu seriu dam na webe tiez mi zobrazi prvych 16 epizod ale ponukne mi nacitat viacej dalsich epizod a tak sa dostanem napr az k dalsim 30 epizodam...Prosim skuste sa na to pozret podla mna to bude banalita..

**Comment by haragiro** [comment]
uz sa zobrazuju dalsie, fixnute 2dni spat, stale vsak chyba oznacenie epizod...

**Comment by jose1711** [comment]
closed via e25b8a3
