### ISSUE TITLE
zobrazenie najnovsich epizod+OZNAZECENIE CISLAMI

### ISSUE THREAD

**Issue by bodyguardroman** [kodi-czsk/plugin.video.joj.sk#35]
doplnok je funkčný,ale mohol by si doplniť toto?:
na uvodnej stránke sa objavuju najnovšie epizody,mohol by si to doplniť do doplnku?
"najnovšie videa"
+cislovanie epizod ako to maju na webe,že napr.som mama ep.6,atd...
https://videoportal.joj.sk/cesko-slovensko-ma-talent
pri vsetkych videach je polozka:najnovsie videa
https://www.joj.sk/cesko-slovensko-ma-talent/vystupenia doplnit tu polozku vystupenia.
 Oni tie videa najprv daju do sekcie "najnovšie" to je ta uvodná stranka,až neskor ich presunu do hlavnej zložky...Keď si das hocikaju relaciu maju pri nej sekciu,že "najnovšie".to v doplnku není,,,

**Comment by jose1711** [comment]
pre prvu cast requestu pozri https://github.com/jose1711/plugin.video.joj.sk/tree/show_episodes
