### ISSUE TITLE
LG WebOS port

### ISSUE THREAD

**Issue by rchovan** [kodi-czsk/plugin.video.joj.sk#5]
@lzoubek , @Kuci , @mx3L , @E000001 
Zdravim, 
vedeli by ste tieto doplnky portovat aj na LG WebOS TV ? Mohol by som pomoct s testovanim.

**Comment by E000001** [comment]
Když mi z LG pošlou domů nějakou jejich našláplou telku s tímto OS, tak by to možná šlo :D

**Comment by Kuci** [comment]
Podla [tejto stranky](http://developer.lge.com/webOSTV/sdk/web-sdk/webos-tv-emulator/introduction-webos-tv-emulator/) ani nie je nutne mat nejaku LG telku, staci emulator. Avsak, Kodi na smart telkach nepojde, kedze zatial co som videl, aplikacie tam behaju v JavaScript. Takze tu sa uz nebavime o portovani pluginov, ale o vytvarani novych aplikacii.

**Comment by rchovan** [comment]
To ze Kodi na WebOS nepojde som sa docital aj na oficialnom fore http://forum.kodi.tv/showthread.php?tid=200487, preto sa pytam ci mate chut portovat/vytvorit  app pre WebOS. 
Ak som to spravne pochopil, tak na WebOS bezia aj HTML aplikacie: http://developer.lge.com/webOSTV/develop/web-app/

**Comment by E000001** [comment]
Sorry, ale já osobně to dělám hlavně proto, že to sám používám. A jelikož nemám TV s WebOS, tak to pro mne nemá význam. Nemohu ale mluvit za ostatní.

**Comment by Kuci** [comment]
Ja mam Panasonic Viera smart tv a aplikacie na ich OS sa tiez robia v HTLM/JavaScript. Po kratkom case som ale dosiel k zaveru, ze zakupit si nejake Raspberry Pi alebo nieco ine a na to dat Kodi a nase doplnky je daleko menej nakladne a casovo narocne riesenie nez pisat nove aplikacie. Navise, Kodi podporuje daleko viacej kodekov atd.
