### ISSUE TITLE
divoke kone

### ISSUE THREAD

**Issue by bodyguardroman** [kodi-czsk/plugin.video.joj.sk#6]
http://divokekone.joj.sk/archiv/2015-06-25-divoke-kone-finale-serie-premiera

Dobry den tento serial premiestnili sem a v kodi uz pri doplnku napise:chyba skriptu(pri tomto seriali).
Mozete to spravit aby to fungovalo?

**Comment by mx3L** [comment]
Dakujem za info, opravene
