### ISSUE TITLE
CS ma talent

### ISSUE THREAD

**Issue by co5mo** [kodi-czsk/plugin.video.joj.sk#8]
zdravim prehratie cs ma talent nefunguje
diel je aktualne viditelny v casti top videos

errorlog:
http://pastebin.com/7GW79PYU

dakujem

**Comment by jose1711** [comment]
tiez som si to vsimol, povodna url bola
http://csmatalent.joj.sk/archiv/2015-09-02-cesko-slovensko-ma-talent-5-premiera (tu cita aj plugin), potom ju zmenili na http://csmatalent.joj.sk/csmt5-archiv/2015-09-02-cesko-slovensko-ma-talent-5-premiera.html

**Comment by jose1711** [comment]
pre opravu treba v subore joj.py (addons/plugin.video.joj.sk/resources/lib) riadok 369 mierne upravit na:
`playerdata = re.search(r'<div\ class=\"(player )?jn-player\"(.+?)>', data, re.DOTALL).group(2).replace('\n',' ')`

forkovat a ziadat o merge nebudem, lebo som hnily ako voš

**Comment by mx3L** [comment]
Vdaka @jose1711, oprava pridana
